### ISSUE TITLE
Add custom error pages

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/elda#104]
An Elda URL which does not fully resolve to an endpoint generates,correctly, a 404 response. Currently, this response is displayed to the user as a default servlet container (e.g Apache Tomcat) error, typically including the software version. This response frequently fails penetration test audit, as it divulges information potentially of use to an attacker.

What we minimally need is custom error pages on which the information displayed is under our control, and does not reveal version information. This applies equally to other 50x and 40x errors.

What we would *like* would be customisable error pages, which can be styled to the look and feel of the overall deployment. This should be achieved without having to alter the contents (including `web.xml` and `context.xml`) of a standard Elda artefact, such as `elda-common.war`. We want users to be able to deploy the `.war` file without needing to alter it.

The proposal, subject to confirmation that it works, is to use the standard servlet `error-page` directive to nominate default custom error pages in a typically unused part of Elda's address space:

    <error-page>
      <error-code>404</error-code>
      <location>/_errors/404.html</location>
    </error-page>

This would serve the minimal requirement for non-disclosing error responses. Individual deployments could then use Tomcat-specific mechanisms (or equivalents for other application containers), to map the context so that `_errors` took content from other parts of the file system:

    <Context path="/" aliases="/_errors=/var/www/mydeployment/_errors">
    </Context>

**Comment by ehedgehog** [comment]
In a further revision, error pages are now handled by velocity macros and the creation
of specific responses inside Elda: see the reference documentation for Elda's
starting at 1.3.4.
