### ISSUE TITLE
Incorrect preservation of suffix

### ISSUE THREAD

**Issue by der** [epimorphics/elda#106]
Using an instance of Elda with velocity render as default I'm seeing all the links on the rendered page have a ".vhtml" suffix even though the URL being viewed has no suffix. 

This works for some endpoints but not for others (don't know why, separate investigation needed).

In the case where the render is the default renderer suggest not appending suffixes at all.

**Comment by skwlilac** [comment]
FWIW.... I think that if the format has been selected by conneg from a 'generic' URI then the links on the rendered page should also be without suffices.

**Comment by ijdickinson** [comment]
Blocked on #135

**Comment by ijdickinson** [comment]
I realised that I hadn't merged branch issue-106 into master. This is now done, which provides better default behaviour for the dominant case (viewing HTML with the default renderer). It does mean that viewing HTML with a non-default renderer will mean that every traversal will flip back to default renderer. Until we can determine whether the current renderer is default or not (issue #135), that will have to suffice.

**Comment by ijdickinson** [comment]
Following the #135 fix, I've now merged the changes to finally fix this issue into master.
