### ISSUE TITLE
Place delimiters around tokens reported in error messages

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/elda#113]
I've got some bad data that has spaces in a property URI for rdfs:label.  When Elda tries to render this it fails and logs:

[[
Error 500: Exception while writing the response model: http://www.w3.org/2000/01/rdf-schema#seeAlso
]]

It is not obvious that the problem is whitespace in the URL after the #seeAlso.  If the URI were enclosed in angle brackets or other delimitter this error would have been obvious.

**Comment by ehedgehog** [comment]
Accepted as a principle, and assorted messages have '-wrappers round inserted text.
