### ISSUE TITLE
Velocity renderer generates links on b-node property values

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#115]
The velocity renderer presents bnode property values as clickable links that cannot be followed successfully.

For example: using the master branch of `bwq-lda` project:

- run `mvn clean package tomcat7:run-war` 
- then access `http://localhost:8080/elda/def`

This generate a page that lists a number of vocabularies with bnode's for contributors. The resulting HTML contains markup if the form:

`<h4 class="resource-uri"><a href="_:-b6d9076:14acfaf5329:-7ed5">_:-b6d9076:14acfaf5329:-7ed5</a></h4>`

which provides a non-dereferencable 'magic' URI reference for the b-node.

The href should be omitted from the bnode, as should the link-text.

![bnode-links](https://cloud.githubusercontent.com/assets/3800472/5684306/fc067ba0-9826-11e4-97f9-eff2ceb20bac.png)

**Comment by bwm-epimorphics** [comment]
Looking at the fix in my environment, it does what it says on the tin.  It no longer createslive hyperlinks for bnodes.

Is there a reason to still display a bnode id?  Would it be better not to omit the id if the resource is a bnode?

**Comment by ijdickinson** [comment]
If you look at what the xslt stylesheet does, it pulls out the name property to use as the bnode header:

http://environment.data.gov.uk/def/bathing-water/

The problem with that is that you can then not use that property value as a filter - there's no affordance for filtering resources whose `author.name` is Stuart Williams. I think it needs something in the header to indicate what sort of thing this is.

An alternative would be to put some generic phrase like "anonymous resource", perhaps with the bNode ID as a tooltip. The utility of the bNode ID is that it, in principle, means that you can see where else that resource might appear in the results graph. But I'll freely admit that that is an edge case.

It's also worth noting that, whatever the default, this is something that installers can override in the site-local velocity macros.

**Comment by bwm-epimorphics** [comment]
Regarding using the label:

What the velocity renderer does for resources with URIs is use the label in the 'title' bar of the html section, and repeat the label property in the list of properties.  It would be consistent to follow that pattern for b-nodes as well and that would allow filtering by label.

If I recall correctly, the Xslt renderer leaves the title blank if there is no label on the bnode.

This not something where I have a strong view.  I was concerned about the hyperlinks that 404 and that is clearly fixed.  The rest is polishing.  

What the velocity renderer is doing with uri resources is display the label twice, once as a title and once as a property that can be used for filtering.  Seems to me to make sense to follow the same pattern for bnodes.

If it were me, I would be tempted to go with leaving the title blank if there is no label.  

However, I am happy for you to do what you think makes sense given what you have heard.

**Comment by ijdickinson** [comment]
Fixes rolled into master for 1.3.5-SNAPSHOT
