### ISSUE TITLE
Velocity HTML Renderer enters infinite loop

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/elda#116]
When resolving a resource R, e.g. http://example.org/def/foo/bar/1, as HTML using the velocity renderer 'out of the box', if  R has a property whose value is a resource whose URI is the start of R's URI, e.g. 

http://example.org/def/foo/bar/1 skos:inScheme http://example.org/def/foo .

then the velocity renderer will enter an infinite loop.

The resource R can be rendered correctly by:

- adding a .html extension to the access URI, e.g. accessing http://example.org/def/foo/bar/1.html
- using a different domain name for the access, e.g. http://localhost/def/foo/bar/1
- using the XSLT renderer

Gist at https://gist.github.com/bwm-epimorphics/10c60c31bd934bd3948f

**Comment by ijdickinson** [comment]
Can't reproduce. I recreated your gist, and it works for me:

![screenshot from 2015-01-17 10 17 12](https://cloud.githubusercontent.com/assets/63979/5788515/77f21ae2-9e32-11e4-86be-ae25b7990348.png)

Off-hand, I can't think of any place where the Velocity renderer cares about sub-strings of URIs. What else can you tell me about your setup? What are the symptoms of the "infinite loop" you refer to? Do you have a stacktrace or log files?

**Comment by bwm-epimorphics** [comment]
Thanks for taking a look at this.  Been banging my head on it for a bit.

Your screen shot shows that the browser accessed localhost:8080/elda/def/foo/bar/1.

The failure condition arises when you dereference the actual URI in the data.  Try pointing the browser at  http://example.org/def/foo/bar/1.  See the second bullet in the list of ways that does work.

If you don't want to mess with your hosts file and ports, you might try modifying the data so that the data is: 

http://localhost:8080/elda/def/foo/bar/1 skos:inScheme http://localhost:8080/elda/def/foo/bar .

Though that is not how I've been seeing it happen.  If that doesn't trigger it for you, then I can try to mirror your setup.

They symptoms of the loop are:

- Tomcat at > 100% cpu utilization for many minutes
- fan gets loud
- no stack trace - have to kill tomcat to recover
- Elda logging says its about to render the result and then it heads of to never never land

I have an apache front end proxying to Elda in Tomcat.  Have had it fail on Elda 1.3.3 and 1.3.4.

My environment is a bit unusual - I'm using docker so that could introduce an issue.  If it doesn't reproduce for you, I can try it in VM instead.  

Note the XSLT renderer is working.  The Velocity renderer is working with  the .html extension and other access URI patterns.

**Comment by ijdickinson** [comment]
The problem is not to do with one URI being a sub-string of another, rather it's when the renderer tries to display a resource that also matches terms in the meta-data graph. I haven't quite got to the bottom of what's happening, but the the renderer is getting stuck building non-terminating hierarchies of `isFormatOf - hasFormat - isFormatOf ...`. Why this is defeating the loop-unrolling code I'm not sure yet.
