### ISSUE TITLE
Velocity generated html for item endpoints could generate filters on list endpoint urls

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/elda#118]
When displaying a resource e.g.

  /foo/bar

as HTML in an item endpoint, the HTML generated by the Velocity renderer includes the facility to generate further requests which filter the view to those results that have a property with a specific value.  This facility is represented by 'require' filters in a popup menu.

The URLs generated for these require links are of the form:

  http://.../foo/bar?prop=value

Since http://.../foo/bar is an item endpoint, these will always display the same item as the page they are on.  Consider instead having these URLs be to an appropriate list endpoint which would list similar resources with the appropriate filter.

For its 'more like this' links, the XSLT renderer assumed that truncating the URL of the item back to the last '/' in the URL would give the URL of an appropriate list endpoint and would generate URLs of the form:

http://.../foo?prop=value

**Comment by ijdickinson** [comment]
Sorry, I don't understand. Why should `/bar` be deleted from the URL? Under what circumstances?

**Comment by ijdickinson** [comment]
I've uploaded a snapshot for the proposed fix to the repo. Please test.

**Comment by bwm-epimorphics** [comment]
Tested:  looks good.

**Comment by ijdickinson** [comment]
Fix released into master branch for 1.3.5-SNAPSHOT
