### ISSUE TITLE
VelocityRender generating java.lang.IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#126]
Somewhere between elda-1.3.4 and elda-1.3.5 something got broken around the work on issue #116

    `http://localhost/elda/doc/bathing-water-quality/compliance/point/03600`

displays a list of compliance assessments for Spittal. These run from 1998 to the present day.

Under 1.3.4 the  first page of 10 successive compliance assessments for Spittal are displayed correctly thus (note the visually repetitive structure):

![working](https://cloud.githubusercontent.com/assets/3800472/6151821/4d32173e-b210-11e4-8d1d-2c74342a0cdf.png)

Under 1.3.5 the first entry (1998) displays correctly, the second entry (1998), which should repeat detail for bathing waters and smpling points, omit details of some subordinate entries and (presumably) the familiar exception:

    Invocation of method 'get' in  class java.util.ArrayList threw exception java.lang.IndexOutOfBoundsException: Index: 2, Size: 0 at partials/overrides.vm[line 16, column 35]

which loses the remaining entries from the page.

![broken](https://cloud.githubusercontent.com/assets/3800472/6151844/7500fb90-b210-11e4-96cc-94f644d78779.png)

I've managed to isolate most recent working version of the code and the first broken version:

Most Recent working version: df265c5ee635095434078d78552e92f2f452fcab
First Broken Version: fb322a9ff593d296cc464183be9a65fe1bc4bd90

The commit message on fb322a is:    "Issue #116 - seen() check was testing the wrong object" and the files with commits changes are DisplayHierarchy and DisplayHierarchyTest.

All subsequent versions along the path the current HEAD of the master branch exhibit the same broken behavior.

I'll aim to create a smaller test case (dataset and api config) that gets closer to the heart of the problem.

**Comment by skwlilac** [comment]
Ian,

I've uploaded some test data and an api-config that may help explore this problem as a Gist:

`https://gist.github.com/511b9e8403244d85308d.git`

They are also available in the test-case branch of the bwq-lda project.

The the configuration does expose the problem, but not in the way that I was expecting!

`http://localhost/elda/anything`

will generate the exception we've been seeing and a truncated page:
```
2015-02-11 18:25:23,480  WARN [http-nio-80-exec-6] (VelocityRendering.java:124) - Invocation of method 'get' in  class java.util.ArrayList threw exception java.lang.IndexOutOfBoundsException: Index: 2, Size: 0 at partials/overrides.vm[line 16, column 35]
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'get' in  class java.util.ArrayList threw exception java.lang.IndexOutOfBoundsException: Index: 2, Size: 0 at partials/overrides.vm[line 16, column 35]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
```

However

`http://localhost/elda/anything?_properties=*.*`
`http://localhost/elda/anything?_view=basic&_properties=*.*`
`http://localhost/elda/anything?_view=basic&_properties=samplingPoint.lat,samplingPoint.long,samplingPoint.northing,samplingPoint.easting`

all unexpectedly render the the correct page. The use of _view=basic removes the DESCRIBE based view query, replacing it with a basic property chain viewer that includes just `type,label` which in are augmented by `_properties=...`

One orther things to observe:

`http://localhost/elda/anything?_view=basic&_properties=samplingPoint.lat,samplingPoint.long`

generates a 'strange' page because (I think) the mapping is triggered by the presence of lat/long, but operates on northing/eastings which have not been brought into the view.

**Comment by ijdickinson** [comment]
So this turns out not to be a bug in core Elda, but in the `overrides.vm` extensions in `bwq-lda`. I've committed a fix there, and am closing this issue. Follow-up discussion, including the "strange page" mentioned in the last para should probably happen in the `bwq-lda` issues tracker.
