### ISSUE TITLE
Empty _properties causes error

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/elda#127]
Passing `_properties=` as a URL parameter causes Elda to raise an error. I think this is incorrect: I am asking for that page with a list of precisely no extra parameters, which ought to be OK. It's the kind of thing that can easily arise when generating API calls programatically.

**Comment by ehedgehog** [comment]
Exactly what was the reported error?

[If I remember correctly, Elda discards any and all query parameters
with no value before it gets anywhere near checking which ones
they are; would that account for the error reported?]

**Comment by ijdickinson** [comment]
Actually, it looks like it's a Velocity renderer bug, and not the cause of my API call not working (but it was the reason that my *investigation* of why my API call was not working was itself not working)
