### ISSUE TITLE
License configuration for response pages.

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#128]
In some circumstances it is desirable to associate a data licence with a response *page* eg. one of many Creative Commons licences or the UK Gov  OGL. It is not sufficient to merely express the licence on the metadata for a given dataset, the licence needs to be imprinted on the derived generated pages themselves.

It would be useful if elda had a configuration for setting a licence generated pages at the API and endpoint levels.

**Comment by ehedgehog** [comment]
Experimentally in 1.3.18.
