### ISSUE TITLE
elda-assets/..../webapp and elda-standalone/..../lda-assets don't match

### ISSUE THREAD

**Issue by rwalkerands** [epimorphics/elda#133]
Doing:
<pre>diff -r elda-assets/src/main/webapp elda-standalone/src/main/webapp/lda-assets</pre>
shows that those two directories don't match up.

Fine, I guess, except that `elda-assets/src/main/webapp/css/result.css`
refers to `../images/standalone-banner.png`, but there's no such file.

`standalone-banner.png` _does_ occur in `elda-standalone/src/main/webapp/lda-assets/images` (and `elda-standalone/src/main/webapp/lda-assets/velocity/images`).

There may be other gotchas lurking as a result of differences between the two directories, but this is the one that bit me just now: I'm using (more precisely, SISSVoc is using) the assets from elda-assets as `/lda-assets`, and therefore I'm getting a 404 for `/lda-assets/images/standalone-banner.png`.

**Comment by ehedgehog** [comment]
As of 1.3.18, elda-standalone is build using elda-assets and the only standalone-specific assets
are meant to support the example specs.

**Comment by rwalkerands** [comment]
Uh ... doesn't the particular issue remain?

I.e.: `elda-assets/src/main/webapp/css/result.css` still refers to `../images/standalone-banner.png`, and there's still no such file.

Someone who has deployed `elda-assets.war` as, say, `/lda-assets ,` who refers to `/lda-assets/css/result.css`, will still get a 404 for `/lda-assets/images/standalone-banner.png`.
