### ISSUE TITLE
Velocity renderer does not pick up visibleSparqlEndpoint setting

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/elda#136]
@skwlilac notes that the Elda config contains a setting for the public identity of the SPARQL endpoint, and that, if set, this should be used in preference to that returned in the page metadata.

**Comment by ijdickinson** [comment]
@skwlilac  Re: your comment on e73f1b248cbaba631cbbbb977bafa79f3f4192ab: the problem was that the state of master had moved on, and the branch was stale. I've merged master into the issue-136 branch - please try again.

**Comment by skwlilac** [comment]
That's working now. Thanks.
