### ISSUE TITLE
JSON renderer encoding issues (UTF-8)

### ISSUE THREAD

**Issue by ColinMaudry** [epimorphics/elda#145]
Although the data stored in the repository (Fuseki2) is well encoded, when I get JSON results, characters with accents such as é, è or ù get corrupted.

Example: https://www.data.maudry.com/fr/datasets/tarification-a-lactivite-quel-impact-sur-les-readmissions-a-lhopital.json

With CSV, HTML and XML, no problem:

* HTML: https://www.data.maudry.com/fr/datasets/tarification-a-lactivite-quel-impact-sur-les-readmissions-a-lhopital
* XML: https://www.data.maudry.com/fr/datasets/tarification-a-lactivite-quel-impact-sur-les-readmissions-a-lhopital.xml
* CSV: https://www.data.maudry.com/fr/datasets/tarification-a-lactivite-quel-impact-sur-les-readmissions-a-lhopital.csv

I wonder if there could be something wrong with my configuration, as it's quite a core feature and I wouldn't expect it to be buggy.

My API configuration: https://github.com/ColinMaudry/datagouvfr-rdf/blob/master/api/specs/datagouvfr.ttl

## Environment

I was using 1.3.1 and I just upgraded to 1.3.12, same issue. Elda is installed on Tomcat 7.0.57 with Java 1.8.0_31-b13.

**Comment by ColinMaudry** [comment]
OK, I had searched in the Google group with "JSON" and hadn't found anything. With "encoding" I found this thread:

**Comment by ehedgehog** [comment]
I'm open to making an explicit charset declaration in the output mimetype, but not today.

**Comment by ColinMaudry** [comment]
I see I should add the property `api:mimeType "text/html; charset=utf-8"` to the JSON renderer specified in my API config.

Problem: the JSON renderer is not specified in my API config, it's just there, available, defined somewhere upstream.

Question: where is the JSON renderer defined, so that I can add this property?

**Comment by ehedgehog** [comment]
Elda's JSON media type now (in snapshot) specifies charset utf-8.
