### ISSUE TITLE
'Poison stream' changes mask other errors, reduce helpfulness for debugging

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/elda#151]
I'm trying to debug some changes using `elda-standalone` at the moment. For reasons I don't yet understand, the velocity renderer is failing with 

```
org.apache.velocity.exception.ResourceNotFoundException: 
Unable to find resource 'index.vm'
```

That's not the problem I'm reporting however. The problem is that, this error having occurred, the only output visible on the output page is

```
STREAMING ERROR <=>'<=>"<=>
```

I believe this is a result of the fix for #46. Two problems occur to me:
- This tells me nothing about the problem that occurred. Worse, I'm not trying to stream the output, so it's actively misleading. I never liked the salmon-pink error pages, but they at least give _some_ indication of the problem. I had to grep the log output to find the root cause, quoted above.
- Even in the case that I was streaming, and the change is therefore intended to help me by not silently truncating output, this still won't help me as a developer to know what went wrong and how to fix it.

**Comment by ehedgehog** [comment]
.Whats in the log

**Comment by ijdickinson** [comment]
Log contents: https://gist.github.com/ijdickinson/30683c08576b25d158b6

**Comment by ehedgehog** [comment]
Yes, having some of the exception text added to the poision
string is something that got overlooked. (Although the developer
is assumed to have access to the logs, and the exception is logged.)

The velocity renderer is (currently) a streaming renderer. What "streaming"
means in this context is that the renderer is doing computations to produce the
next pieces of output, and the output stream it's supplied with is
connected (mostly) directly to the connection back to the client,
and the 200 OK has already been sent.

Non-streaming is when the renderer builds up a result string aand
then sends it back all in one go. The overhead is that the result
string must be given space between rendering and sending.

A code-responsibility way to describe it is that non-streaming
renderers do their work in (an implementation of) Renderer.render,
while streaming renderers do their work in (an implementation
of) BytesOut.writeAll.

I note also that RouterRestlet.wrap's created StreamingOutput
object re-throws any caught exception. This is probably why the
response page looks so horrible -- there's no pink page for the
not-found exception, even if pink page handling works during
StreamingOutput.

**Comment by ijdickinson** [comment]
> Yes, having some of the exception text added to the poision
> string is something that got overlooked. (Although the developer
> is assumed to have access to the logs, and the exception is logged.)

Reasonable. It would be helpful, now that requests have reference numbers, to show the reference in the displayed error so that it's easier to locate the full error report in the log file.

> A code-responsibility way to describe it is that non-streaming
> renderers do their work in (an implementation of) Renderer.render,
> while streaming renderers do their work in (an implementation
> of) BytesOut.writeAll.

Parenthetically, and probably should be in a separate ticket, but I found working on the Velocity renderer that the current renderer API is very complex. I certainly picked up no clue from the current code of the distinction in responsibilities between streaming and non-streaming modes. I think the whole renderer API could do with refactoring at some point.

**Comment by ehedgehog** [comment]
Updated the poisining code.

Made the Velocity and JSON renderer poison strings less
    puzzling. Ensured that the exception message is copied
    into the streaming output. Do not re-throw the provoking
    exception.

I'm not sure that the reference numbers are available at
that point in the code. They're held in a thread-local variable
and I don't know if the same thread runs the streaming output
as handles the Elda request/response generation (which
creates a StreamingOutput object for Jersey to invoke
as it pleases). Investigations are continuing.

Yes, the renderer API is too complicated. (I had a note
somewhere to fix this but it never made it into the
issues list). It's not so much refactoring that it needs
as throwing bits away.

**Comment by ijdickinson** [comment]
OK, it's better, thanks. It's still not clear to me that the `<=>'<=>"<=>` is useful in HTML output: HTML parsers are, by design, very forgiving of ill-formed input.

> I'm not sure that the reference numbers are available at
> that point in the code. They're held in a thread-local variable
> and I don't know if the same thread runs the streaming output
> as handles the Elda request/response generation

My advocacy is to add the code to check the table of thread-local variables at the error generation point. If the reference information is there, you can use it. If not, the overhead isn't going to matter because the code is in a non-working state anyway.

**Comment by ehedgehog** [comment]
"HTML parsers ... very forgiving of ill-formed input ..." Yes. (Grinds teeth).

Hmm. I've talked myself into a bug. When the error is logged in the
StreamingOutput, it's /already/ assuming that its inside the same
thread as the one that created the BytesOut object. That needs to
be justified or removed.

(The real problem I see with my paranoid head on is that
request A could be handled by thread X with ID 1 and
concurrently request B could be handled by thread Y with
ID 2. Both response/StreamingOutput objects get handed
back to Jersey which then could run B's StreamingOutput 
on thread X and A's on Y, *swapping the IDs*. Why would
anyone do this? Dunno, but if they're not /required/ to use
the same thread they might find a reason to rebind them
differently ...)

**Comment by ijdickinson** [comment]
Closing as obsolete
