### ISSUE TITLE
Elda logs every decision *not* to reload the router config at INFO level

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#155]
The elda log stream currently has lots of messages of the form:

```
2015-27-06 12:27:45.717  INFO [http-bio-80-exec-4] (ELog.java:45) - []: don't need to reload router, will check again later.
```

These should only be generated for debug logging, or not at all. They are not useful in a normal operational log.

**Comment by ehedgehog** [comment]
Fixed in .17; "don't need" messages have been dropped, "reloading" and
"using existin" messages are now DEBUG level.
