### ISSUE TITLE
On a query parse exception the defective query is not visible in the log.

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#157]
Even at a debug log level, ELDA can throw a queryParseException and fail to expose the defective query in the log file, making it difficult it determine what needs to be corrected.

**Comment by ehedgehog** [comment]
Various calls to QueryFactory.create (whcih is the ARQ method
for parsing and checking a SPARQL query) were not catching
errors and reporting them to error pages correctly.
There's now a QueryUtils.create which converts errors to
APIExceptions which can supply the message -- including
query -- to the appropriate error page.
