### ISSUE TITLE
Query parameters api:sort, api:orderBy

### ISSUE THREAD

**Issue by iaptsiauri** [epimorphics/elda#159]
I have the endpoint which lists all games which include {name} parameter and what I want to implement currently is to give user option of choosing the ordering of the result.
```
games?name={game}
```
Something similar as:
```
games?name={game}&order={order}
```
you can see the partial implementation of my endpoint. as you can see api:orderBy is statically written. 
```
    api:selector [
        api:where " ?item a epic:Game . ?item epic:Name ?name . FILTER (regex(?name, ?game, 'i')) " ;
        api:orderBy "DESC(?name)"
    ]
    .
```

**Comment by ehedgehog** [comment]
If I understand correctly you want to allow the user (the thing
that is querying Elda) to specify an ORDER BY of their free choice.

 I suggest you try

    api:orderBy "{order}"

You will have to declare `order` as a short name for some new
property and then the user can write

    games?name=nameofgame&order=DESC(nameofpropertytosortby)

[UNTESTED]

**Comment by iaptsiauri** [comment]
@ehedgehog 
Thanks for the response, yes you understood the issue correctly. Unfortunately I have tried your preposition and it didn't work. Here is the generated query
```
SELECT DISTINCT ?item
WHERE {
GRAPH <https://graph.epic.games> { ?item a epic:Game . ?item epic:Name ?name . FILTER (regex(?name, ?game, 'i')) } }  ORDER BY {order} OFFSET 0 LIMIT 50
```
I also tried to substitute ```api:orderBy "{order}"``` with ```api:orderBy "{?order}"``` but in this case I was getting same response of 500. Order by was generated  ``` ORDER BY {"Name"}```

**Comment by ehedgehog** [comment]
Hmm. I think this is a bug, but I also don't think the LDA spec is
precise enough to be sure. The value of api:orderBy is not being
variable-expanded at any time, so the name value (which  changes
on each query) doesn't get inserted into the string.
I'll have a think about this and raise an issue if required.

**Comment by ehedgehog** [comment]
Both api:orderBy and and api:sort should repsect {} as of 1.3.18.
