### ISSUE TITLE
Performance issues with large TDBs

### ISSUE THREAD

**Issue by wood-chris** [epimorphics/elda#167]
This is less of an issue, more of a general question (and so apologies if it should be asked somewhere else).

I have a tdb which will have > 5m triples. I'm looking at using elda to act as an interface for this dataset - are there any performance issues I need to consider, or any particular configuration aspects I could experiment with?

**Comment by ehedgehog** [comment]
The only advice I can offer is: don't try and make the Elda
queries too complicated. "Too" means getting to grips with the 
performance properties of your SPARQL server (which need not
be Fuseki, but if it is, the Jena mailing list would be a place to
ask). Elda's generated queries are pretty straightforward but
sometimes you may need to craft fragments of SPARQL and use the features
of Elda that allow you to embed them in the generated query.

Chris
