### ISSUE TITLE
href rewriting

### ISSUE THREAD

**Issue by wood-chris** [epimorphics/elda#169]
Hi,

I've been playing around with the 2 versions of elda (i.e. the single instance jar version using jetty, and the version with 2 war files).

I've noticed that on the rendered html page from the single jar version that all hrefs links for each item listed are written as `http://localhost:8080/about?resource=<some_uri>`, whereas the war version doesn't do any rewriting of href links.  My 2 `config.ttl` files are the same I know I could use mod_rewrites to rewrite the urls to have the same effect but I wondered if I'd overlooked a whole configuration file somewhere?!

**Comment by ehedgehog** [comment]
Could you be more specific about what you did, including which version of Elda you were using, which rendering (format) you were using, and what the URL was for the page showing the above
behaviour?

My /guess/ is that you used a /about link which created a base URI containing the
about?resource=URI and that became the base URI for the generated links. The
elda-common version (two .wars, one for lda the other for assets) probably won't 
have a configuration that has an about link -- it depends on the Elda version I think.

There's no extra config file you need to know about [1]

Chris
[1] well there's an auth config but that's not normally present or used
