### ISSUE TITLE
Velocity renderer prefix handling broken when "&_count=yes" applied.

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#172]
`&_count=yes` causes elda to count the total number of items returned across all the pages of a list endpoint. However, it also adds a comment line to the elda select query that's made available for presentation to the user. The presence of this `# comment` may be throwing off the client side code that supports prefix handling in the query form at the bottom of the page.

When `&_count=yes` the preconfigured prefixes may present as expanded, and there is some 'debris' from any prefixes passed across in the query being rendered.

**Comment by ijdickinson** [comment]
@skwlilac What's the easiest way for me to reproduce this issue?

**Comment by skwlilac** [comment]
Use our (local) bwq-lda project. Uncomment line 164 of `etc/elda/conf.d/elda/environment.data.gov.uk-bwq.ttl` (change "yes" to "optional" on that line) and then try `http://localhost:8080/elda/doc/bathing-water?_count=yes`

**Comment by ijdickinson** [comment]
Line 164 no longer has a `"yes"` on it. What line should it be now?

**Comment by skwlilac** [comment]
Line 166 (which I've already tweak to say "optional" just needs to be uncommented)

**Comment by ijdickinson** [comment]
Thanks Stuart. I confirm I can see the problem, but I think some upstream changes are going to be needed first. In particular, the comment-handling code is part of qonsole, but that component needs some general updating. This may take a while!

**Comment by ijdickinson** [comment]
@skwlilac The `issue-188` branch has an updated version of Qonsole, which should address this problem. Please check and let me know if I can merge into master. Thanks.

**Comment by skwlilac** [comment]
@ijdickinson  Unfortunately the qonsole panel seems to be generic and the select and view query tabs that were previously present are missing for me. So not able to check:

http://localhost:8080/elda/doc/bathing-water?_pageSize=2&_view=basic

![image](https://user-images.githubusercontent.com/3800472/28455652-ae4f5c66-6df7-11e7-808d-22a511c704bb.png)

**Comment by ijdickinson** [comment]
The same example works on my machine. @skwlilac and I have discussed offline, & agreed to defer further debugging until we can sit down together in the location, probably early next week.
