### ISSUE TITLE
`&_pageSize` is not being retained in `next` and `first` links

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#174]
The `next` and `first` links on an ELDA result page do not retain any given value for `_pageSize`.

e.g. the JSON output from `http://environment.data.gov.uk/doc/bathing-water.json?_view=basic&_pageSize=2` is as follows:

```
{
	format: "linked-data-api",
	version: "0.2",
	result: {
		_about: "http://environment.data.gov.uk/doc/bathing-water.json?_pageSize=2&_view=basic",
		definition: "http://environment.data.gov.uk/meta/doc/bathing-water.json?_view=basic",
		extendedMetadataVersion: "http://environment.data.gov.uk/doc/bathing-water.json?_pageSize=2&_view=basic&_metadata=all",
		first: "http://environment.data.gov.uk/doc/bathing-water.json?_page=0&_view=basic",
		isPartOf: {
			_about: "http://environment.data.gov.uk/doc/bathing-water.json?_view=basic",
			definition: "http://environment.data.gov.uk/meta/doc/bathing-water.json?_view=basic",
			hasPart: "http://environment.data.gov.uk/doc/bathing-water.json?_pageSize=2&_view=basic",
			type: [
				"http://purl.org/linked-data/api/vocab#ListEndpoint"
			]
		},
		items: [{
			_about: "http://environment.data.gov.uk/id/bathing-water/ukc2102-03600",
			label: [{
				_value: "Spittal",
				_lang: "en"
			}],
			type: [
				"http://environment.data.gov.uk/def/bathing-water/BathingWater",
				"http://environment.data.gov.uk/def/bathing-water/CoastalBathingWater"
			]
		}, {
			_about: "http://environment.data.gov.uk/id/bathing-water/ukc2102-03700",
			label: [{
				_value: "Bamburgh Castle",
				_lang: "en"
			}],
			type: [
				"http://environment.data.gov.uk/def/bathing-water/BathingWater",
				"http://environment.data.gov.uk/def/bathing-water/CoastalBathingWater"
			]
		}],
		itemsPerPage: 2,
		next: "http://environment.data.gov.uk/doc/bathing-water.json?_page=1&_view=basic",
		page: 0,
		startIndex: 1,
		type: [
			"http://purl.org/linked-data/api/vocab#Page"
		]
	}
}
```

specifically URI values of the `first` and `next` keys do not include `&_pageSize=2`.

This means that elda paging will only work when the default page size is in use.  Otherwise the item sequence across successive pages in sequence is disturbed if paging is accomplished by following `next` links.

This affects elda version 1.3.14 and later and probably affect earlier versions aswell.

**Comment by ehedgehog** [comment]
I think the change occurred between versions .12 and .13 
(I've had problems rebuilding versions) judging by the code.
There's a specific call used to strip off the page information
from the generated URI and it looks like it has been applied to
something it shouldn't have been.

Specificially APIEndpointImpl line 238 strips the page parameters 
from the URI used for the entire list. I believe that the
_pageSize parameter (but NOT the _page parameter) should
be retained. This seems to fix the presenting problem but it
needs a coat of thinking about in case there are other
subtleties
