### ISSUE TITLE
RDFS inference with local datafile?

### ISSUE THREAD

**Issue by zednis** [epimorphics/elda#176]
Is there a way to turn on RDFS inference when specifying a local datafile?

```
ex:api
    a api:API ;
    api:sparqlEndpoint <local:data/example.ttl> ;
    # turn on RDFS inference
    ...	
```

**Comment by ehedgehog** [comment]
No. (local: is mostly for experimenting so that you don't have to set
up a fuseki.)

But you can construct a file with the RDFS closure in it
and point local: to that.

Chris
