### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by rwalkerands** [epimorphics/elda#177]
We seem to be increasingly a "victim of our own success" in deploying an instance of elda-lda.

We now semi-regularly have days in which a user will deploy multiple new or updated spec files, triggering a reload of all spec files (we now have over 100 spec files, each with 15 or so endpoints).

In the last week I've twice had to restart our Tomcat because of a serious memory leak that _seems_ to be related to the reloading of the spec files.

Yesterday I used VisualVM to try to track down the problem. There seem to be multiple instances of the configuration, one created each time the reloading of the spec files is triggered.

Each copy of the configuration holds large HashMaps containing (for example) all the endpoint mappings.

The attached screenshot is from VisualVM. It is filtered by class name limited to "com.epimorphics...". Note the 22 instances of DefaultRouter and SpecManagerImpl (plus two other related classes). 22 seems to be about the number of times the spec files have been (re)loaded. I.e., I did a heap dump, saw that the numbers were 21, then triggered a reload by editing one of the spec files, and then did another heap dump, and the numbers were then 22.

I tried to find why the code does this. In `RouterRestlet.getRouterFor()` there are two calls to `RouterRestletSupport.createRouterFor()`; the second one seems to be the one associated with the reloading of spec files.

`RouterRestletSupport.createRouterFor()` invokes `new SpecManagerImpl()` and passes the resulting object to `SpecManagerFactory.set()`.

I note the class comment at the top of `SpecManager.java` that says "... The (singleton) instance of the SpecManager ...", but `SpecManagerFactory.set()` is _not_ a setter! It _adds_ the value you pass in to an `ArrayList<SpecManager>`.

So each time there is a reload, a new `SpecManagerImpl` is created, which contains a new `DefaultRouter`. And because these new objects are stored away in an `ArrayList` and never removed, they are never garbage collected.

![screen shot 2017-02-13 at 6 05 39 pm](https://cloud.githubusercontent.com/assets/8368914/22906079/0cf54668-f297-11e6-8174-79eac0b7feef.png)

**Comment by ehedgehog** [comment]
What version of Elda?

**Comment by rwalkerands** [comment]
Oops, sorry. We are running 1.3.20.

**Comment by ehedgehog** [comment]
Hmm. It's very plausibly a bug. But it looks like it may be a subtle bug -- I don't
think it's right just to replace the `managers` list with a single value. Note that
RouterRestletSupport addBaseFilepath(String baseFilePath) says:

	/**
	    Add the baseFilePath to the FileManager singleton. Only do it
	    once, otherwise the instance will get larger on each config load
	    (at least that won't be once per query, though). Just possibly
	    there may be multiple servlet contexts so we add a new only only if 
	    its not already in the instance's locator list.
	*/

which suggetst the correct fix is to overwrite an existing SM and add
a new one. 

I'll continue to look at this one.

Chris

**Comment by rwalkerands** [comment]
Subtle indeed.

FWIW catalina.log has an entry "adding locator for '/usr/share/tomcat/webapps-ands/lda/'" for every config file reload.

So "only do it once" is not happening.

**Comment by rwalkerands** [comment]
Looking good in our test environments.
