### ISSUE TITLE
Is there a way to specify additional query properties to use with SPARQL endpoint?

### ISSUE THREAD

**Issue by zednis** [epimorphics/elda#178]
I would like to add a vendor-specific query parameter to SPARQL endpoint requests.  Is there an elda extension that would allow me to specify this parameter and it's value?

e.g. ruleset={value} in http://localhost:8060/v1/graphs/sparql?query={query}&ruleset={rulesetname}

**Comment by ehedgehog** [comment]
The _where=SPARQL URL parameter splices the SPARQL into the Elda-generated query.
But you would have to be very careful to get the syntax right -- eg remember that spaces
would have to become +.

I suspect you're better off just adding shortname declarations for all the properties
you might want to use in a vendor-specific way.

Chris
