### ISSUE TITLE
Velocity Renderer: rendering of links to resources with URL of the form .../-

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/elda#197]
Property values that are resources with URLs of the form `http://example.com/foo/bar/-` are rendered on the page as an empty `<a>` element.

This is a problem in the EPO site where we have resources with URLs of that form.

The render should put some text inside the anchor element, e.g. 

    <a href='...'>-</a>.

**Comment by ijdickinson** [comment]
In discussion with @bwmcbride, my proposal is that we use the previous path segment for URIs that end with a hyphen character:

    <a href='http://example.com/foo/bar/-'>bar/-</a>

**Comment by ijdickinson** [comment]
@bwmcbride I've committed a fix for this in the `issue-197` branch if you can please try it.

I would also note that:

- it would be better for those resources to have a meaningful `rdfs:label`, which will be used preferentially to any treatment of the URI
- you can customise the rendering of a resource for any given deployment of Elda by overriding the Velocity template `resource-links.vm`

**Comment by ijdickinson** [comment]
Closing as obsolete
