### ISSUE TITLE
incorrect 500 Error on _count=yes

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/elda#198]
Sending a request with _count=yes to endpoint with count explicitly forbidden e.g.

http://lr-pres-staging-b.epimorphics.net/data/ppi/transaction-record.json?propertyAddress.postcode=BS2%208BS&_count=yes

returns a 500 error (internal server error) instead of a 400 bad request error.

**Comment by ehedgehog** [comment]
The example is from Elda 1.3.20 and the problem was fixed
in a subsequent Elda release. A test is being added to the imminent release.

**Comment by bwmcbride** [comment]
Thanks Chris.
