### ISSUE TITLE
_pageSize=0 generates 500 internal server error

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/elda#199]
Sending a request with an _pageSize parameter of 0, e.g.

http://lr-pres-staging-b.epimorphics.net/data/ppi/transaction-record?propertyAddress.postcode=BS2%208BS&_pageSize=0

results in a 500 internal server.

This should either be legitimate request (why wouldn't it be) or a 400 bad request error.

**Comment by ehedgehog** [comment]
Done.
