### ISSUE TITLE
Broken URI in standard ELDA config?

### ISSUE THREAD

**Issue by dr-shorthair** [epimorphics/elda#200]
In 
https://github.com/epimorphics/elda/blob/master/vocabs/elda_api.ttl 
this prefix is defined
@prefix elda:    <http://www.epimorphics.com/vocabularies/lda#> .
but the URI is not currently alive :-(

**Comment by ehedgehog** [comment]
The URL is now live and tests have been added to ensure that this is maintained;
the next version of Elda will have these tests in it.
