### ISSUE TITLE
Versioned documentation URLs bad for SEO

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/elda#69]
If I google 'elda quickstart', the top link is to an *old* version of the documentation:

![image](https://cloud.githubusercontent.com/assets/63979/3570689/e8f9ad44-0b53-11e4-8768-66342c9c1350.png)

At the time of submitting this issue, version 1.2.31 is three releases old. What's the use case for versioned documentation URLs? On the face of it, it seems to guarantee that the current documentation is unlikely to be at the top of the search results.

I strongly advocate that we remove version numbers from the documentation URL structure. In the unlikely event that users need to read the documentation from several versions ago, the source is in the git repo.

**Comment by ehedgehog** [comment]
Done as of Elda's 1.3.*.
