### ISSUE TITLE
Add JSON-LD RDF syntax

### ISSUE THREAD

**Issue by jplu** [epimorphics/elda#77]
Hello,

I'm currently working on a project with @rtroncy and we would need to use the JSON-LD RDF syntax. Is-it planned to add this syntax ? Or if not I can propose myself to do it if that fit you.

Best.

Julien Plu.

**Comment by ColinMaudry** [comment]
I would love to see this happening too. Any move in this direction in the past year @jplu ?

**Comment by rtroncy** [comment]
Hello, the project in question is [3cixty](http://3cixty.com/) and its application [ExplorMI360](https://www.3cixty.com/webApp/). The user interface gets data from a SPARQL endpoint, but ultimately, we developed our own api although we still have a backup plan with a particular elda configuration.

**Comment by ColinMaudry** [comment]
Sooo did you manage to get JSON-LD from Elda or you built your API that returns JSON-LD from scratch?

Indeed most SPARQL endpoints can return JSON-LD, but I'd rather use the convenience of an API framework such as Elda.

**Comment by rtroncy** [comment]
Some project partners developed their own API which returns JSON but not JSON-LD.

**Comment by ehedgehog** [comment]
Elda 1.3.18 has an experimental JSON-LD renderer.
