### ISSUE TITLE
JSON-P media type and character set may be incorrect

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#81]
When using the &callback=foo parameter to generate a JSON-P response the response is marked with a media-type of text/javascript and has no specified character encoding.

Some clients presented with a text/* response without a character set may incorrectly guess. Firefox 30.0 on Ubuntu incorrectly presents an elda JSON-P response a being windows-1252 when I suspect that its utf-8.
Try:

    http://environment.data.gov.uk/doc/bathing-water.json?callback=foo

on a browser near you and check the page properties.

Informational RFC4329 "Scripting Media Types" 
(http://tools.ietf.org/html/rfc4329) says

    "   Use of the "text" top-level type for this kind of content is known to
        be problematic.  This document thus defines text/javascript and text/
        ecmascript but marks them as "obsolete".  Use of experimental and
        unregistered media types, as listed in part above, is discouraged.
        The media types,

        * application/javascript
        * application/ecmascript
        
        which are also defined in this document, are intended for common use
        and should be used instead."

Both of these media-types support a charset parameter so that the charset of the payload can be explicitly stated (as does text/javascript - which seems to be regarded as obsolete). It would be better to explictly state the correct charset in the media-type response header than to leave clients to guess.

**Comment by ehedgehog** [comment]
Done.
