### ISSUE TITLE
acceleration: Filter dropdowns

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#88]
Asthetically, I think it would be better if the per-property filter drop-downs were horizontally aligned. I find their current 'ragged right' presentation  distracting. I think right aligned (as their equivalent in the xslt rendering) would be visually nice and easier to run down vertically rather than 'snaking' left and 'right' down through the controls.

[Low priority and personal taste].

**Comment by ijdickinson** [comment]
Closing old issue.
