### ISSUE TITLE
acceleration: Sorting on URI nodes.

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#90]
I see that you can sort on property values, even URI nodes. Sorting URI nodes on the 'spelling' of the URI may not be the best approach. It's probably more useful to sort on an rdfs:label or skos:prefLabel associated with the URI. Give appropriate shortname decls and some non-literal valued property, <prop>:

```
&sort=<prop>.prefLabel,<prop>.label
```

will sort by prefLabel and (in the absence of a prefLabel) by label.

**Comment by ijdickinson** [comment]
There hasn't been any negative feedback on this, so closing.
