### ISSUE TITLE
Acceleration: visual indicator of which filter dialogue buttons have active filters

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/elda#92]
From @skwlilac in issue #89 - suggestion to add a visual indicator to the popover dialogue buttons, to show when that dialog mentions a currently active filter or sort

**Comment by simonoakesepimorphics** [comment]
This feature exists in the current version of ELDA

**Comment by ijdickinson** [comment]
Which probably means that I implemented it and forgot to close the ticket or tag the commit. Feel free to close.

**Comment by ijdickinson** [comment]
Fixed
